name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]       
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: |
        gem install jekyll bundler
        bundle install
    - name: Build the site
      run: |
        bundle exec jekyll build
        
